sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: easychat
    username: root
    password: yedongyu000

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
